"""Regenerate the static HTML pages: python scripts/build_site.py."""
from pathlib import Path
from html import escape
import re
import hashlib
import struct

ROOT = Path(__file__).resolve().parents[1]
SPEC_PATH = ROOT / 'BUILD_SPEC_FINAL_V2.md'
SPEC = SPEC_PATH.read_text(encoding='utf-8')
HEART = '<svg class="pixel-heart" viewBox="0 0 9 8" aria-hidden="true" shape-rendering="crispEdges"><path fill="currentColor" d="M1 0h2v1h1v1h1V1h1V0h2v1h1v3H8v1H7v1H6v1H5v1H4V7H3V6H2V5H1V4H0V1h1z"/><path fill="#c97c7f" d="M1 1h2v1H1z"/></svg>'

def artwork(name, alt='', class_name='scene-art'):
    width, height = struct.unpack('>II', (ROOT / f'assets/pixel/{name}.png').read_bytes()[16:24])
    loading = 'eager' if name == 'wedding-world' else 'lazy'
    return f'<img class="{class_name}" src="assets/pixel/{name}.png" width="{width}" height="{height}" alt="{escape(alt)}" loading="{loading}" decoding="async">'

def versioned(path):
    return f'{path}?v={hashlib.sha256((ROOT / path).read_bytes()).hexdigest()[:12]}'

def pixel_icon(kind='heart'):
    paths = {
        'heart':'M2 3h4v2h4V3h4v6h-2v2h-2v2H6v-2H4V9H2z',
        'church':'M7 0h2v2h2v2H9v2l6 6v4H1v-4l6-6V4H5V2h2z',
        'glass':'M3 1h10v7l-4 3v3h3v2H4v-2h3v-3L3 8z',
        'ribbon':'M4 1h8v2h2v8h-3l1 5-4-2-4 2 1-5H2V3h2z',
        'star':'M7 0h2v5h2v2h5v2h-5v2H9v5H7v-5H5V9H0V7h5V5h2z',
        'plate':'M6 3h6v2h2v8h-2v2H6v-2H4V5h2zM0 0h2v16H0z',
        'envelope':'M0 3h16v10H0zM2 5v2h2v2h2v2h4V9h2V7h2V5h-2v2h-2v2H6V7H4V5z',
    }
    return f'<svg class="pixel-icon" viewBox="0 0 16 16" aria-hidden="true" shape-rendering="crispEdges"><path fill="currentColor" fill-rule="evenodd" d="{paths[kind]}"/></svg>'
NAV = '<a href="index.html#home">Home</a><a href="wedding.html">Wedding Details</a><a href="outfit.html">Outfit Guide</a><a href="faq-gifts.html">FAQ &amp; Gifts</a><a href="gallery.html">Gallery</a><a class="nav-rsvp" href="rsvp.html">RSVP</a>'
HEADER = f'''<header class="site-header"><a class="brand" href="index.html#home" aria-label="Gica and Vho home">G&amp;V</a><nav class="desktop-nav" aria-label="Main navigation">{NAV}</nav><button class="menu-toggle" type="button" aria-controls="mobile-menu" aria-expanded="false">☰ <span>Menu</span></button></header><dialog id="mobile-menu" class="mobile-menu" aria-label="Navigation"><button class="menu-close" type="button" aria-label="Close menu">×</button><p class="brand">G&amp;V</p><nav aria-label="Mobile navigation">{NAV}</nav></dialog>'''
FOOTER = f'''<footer class="site-footer"><div class="footer-landscape" aria-hidden="true"></div><p class="footer-names">Gica &amp; Vho</p>{HEART}<p>Two Players. One Love.<br>One Unforgettable Adventure.</p><p class="footer-date">2.7.27</p></footer>'''

def page(name, title, content, scripts='', opening=''):
    content = content.replace('<img class="stationery-art" src="assets/pixel/invitation-still-life.png"', '<img class="stationery-art" src="assets/pixel/invitation-still-life.png" width="1536" height="1024"')
    if opening:
        scripts = '<link rel="preload" as="image" href="assets/pixel/wedding-world.png">' + scripts
        scripts += "<script>if(!location.hash){document.documentElement.classList.add('opening-pending');document.addEventListener('DOMContentLoaded',()=>document.documentElement.classList.remove('opening-pending'));}</script>"
    html = f'''<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>{title} · Gica &amp; Vho</title><meta name="description" content="Celebrate the wedding of Gica and Vho on February 7, 2027. Wedding details, guest guide, gallery, and RSVP."><meta property="og:title" content="{title} · Gica &amp; Vho"><meta property="og:description" content="Two Players. One Love. One Unforgettable Adventure. 2.7.27"><meta property="og:type" content="website"><link rel="stylesheet" href="css/global.css"><link rel="stylesheet" href="css/pixel.css"><script src="js/config.js" defer></script><script src="js/main.js" defer></script>{scripts}</head><body>{opening}<div id="site-content"><a class="skip-link" href="#main">Skip to main content</a>{HEADER}<main id="main">{content}</main>{FOOTER}</div></body></html>'''.replace('><', '>\n<')
    output = ROOT / name
    html = re.sub(r'(href|src)="((?:css|js)/[^"?]+\.(?:css|js))"', lambda match: f'{match[1]}="{versioned(match[2])}"', html)
    output.write_text(html, encoding='utf-8')

def intro(title, subtitle):
    return f'<header class="page-intro"><p class="eyebrow">Gica &amp; Vho · 2.7.27</p><h1>{title}</h1><p class="subtitle">{subtitle}</p></header>'

opening = f'''<section id="opening" class="opening" aria-label="Wedding invitation" hidden><div class="opening-lockup"><h1>Gica &amp; Vho</h1><div class="ornament">{HEART}</div><p class="opening-line">A New Game Is About to Begin</p><p class="opening-date">2.7.27</p><p class="opening-copy">Two Players. One Love.<br>One Unforgettable Adventure.</p><button type="button" class="btn" data-press-start>Press Start</button></div></section>'''
story = '''<p>Gica and Vho first crossed paths toward the end of 2024. A few encounters later, a conversation on Gica’s birthday became the beginning of something more.</p><p>What followed was a collection of adventures—traveling with family to the UAE, experiencing Vho’s first BLACKPINK concert, exploring Japan together, and discovering that life was simply more fun when they shared it.</p><p>Along the way, Vho became more willing to step outside his comfort zone, while Gica found someone ready to share her adventurous spirit. Somewhere between the big adventures and ordinary days, they began seeing the same future.</p><p>Then came a proposal, a <strong>yes</strong>, and the start of their greatest adventure yet.</p>'''
moments = ''.join(f'<figure><div class="story-scene story-scene--{i}" role="img" aria-label="{alt}"></div><figcaption><span class="story-marker" aria-hidden="true">0{i+1}</span>{label}</figcaption></figure>' for i, (label,alt) in enumerate([('Unexpected Meeting','Pixel illustration of two people meeting on a garden path'), ('Adventures Together','Pixel illustration of a suitcase and a journey through a garden'), ('The Next Chapter','Pixel illustration of a couple walking toward a wedding arch')]))
countdown = ''.join(f'<div><span class="countdown__num" data-countdown="{unit}">00</span><span class="countdown__label">{unit}</span></div>' for unit in ['days','hours','minutes','seconds'])
page('index.html', 'Our Wedding', f'''<section id="home" class="welcome section"><div class="welcome-copy"><p class="eyebrow">You’ve entered our story</p><h2>A little serendipity.<br>A lifetime together.</h2><p>Welcome to our next chapter. We’re so happy to share this day with the people who have been part of our journey. Thank you for being here, and for celebrating with us.</p><div class="ornament">{HEART}</div></div><div class="welcome-scene"><img class="scene-art home-photo" src="assets/story/DSC00330.jpg" width="6000" height="4000" alt="Gica and Vho smiling together at a café" decoding="async"></div></section><section class="countdown-section section"><div class="ornament">{HEART}</div><h2 class="date">2.7.27</h2><p class="eyebrow">Until our next adventure begins</p><div class="countdown" data-countdown-group>{countdown}</div></section><section id="story" class="section story"><div class="section-heading"><h2>Our Story</h2><p class="subtitle">From an unexpected meeting to a life they’re building together.</p></div><div class="story-copy">{story}</div><div class="story-moments">{moments}</div></section><section class="closing section"><h2>Two People. One Journey.<br>A Lifetime of Adventures Ahead.</h2>{HEART}</section>''', '<script src="js/countdown.js" defer></script>', opening)

def venue(id, label, kind, time, place, address):
    query = 'San+Antonio+de+Padua+Parish+Pooc+Silang+Cavite' if id=='ceremony' else 'Cana+at+Silang+Paglinawan+Street+Pook+1+Silang+Cavite'
    return f'''<section id="{id}" class="venue" aria-label="{kind}"><div class="venue-scene venue-scene--{id}" role="img" aria-label="Thematic pixel-art {kind.lower()} setting"></div><div class="venue-content"><p class="eyebrow">{label}</p><h2>{kind}</h2><p class="venue-time">{time}</p><h3>{place}</h3><p>{address}</p><div class="actions"><a class="btn btn-outline" data-map="{id}" href="https://www.google.com/maps/search/?api=1&amp;query={query}" target="_blank" rel="noopener noreferrer">View Map</a><a class="btn" data-directions="{id}" href="https://www.google.com/maps/dir/?api=1&amp;destination={query}" target="_blank" rel="noopener noreferrer">Get Directions</a></div></div></section>'''

def tabs(group, items):
    return f'<div class="tabs" data-tabs="{group}" aria-label="{group}">' + ''.join(f'<a id="tab-{id}" href="#{id}">{label}</a>' for id,label in items) + '</div>'

timeline = ''.join(f'<li><time>{time}</time><span>{pixel_icon(["church","glass","ribbon","star","plate","heart"][["10:00 AM","11:00 AM","12:30 PM","12:45 PM","1:30 PM","4:00 PM"].index(time)])}{activity}</span></li>' for time,activity in [('10:00 AM','Wedding Ceremony'),('11:00 AM','Guest Welcome &amp; Cocktail Hour'),('12:30 PM','Reception Opens'),('12:45 PM','Reception Program Begins'),('1:30 PM','Lunch / Buffet'),('4:00 PM','Program Ends')])
page('wedding.html', 'Wedding Details', intro('Wedding Details', 'Everything you need for our wedding day.') + f'''<div id="events" class="section event-section">{venue('ceremony','The Promise','Wedding Ceremony','10:00 AM','San Antonio de Padua Parish','Pooc, Silang, Cavite')}{venue('reception','The Celebration','Wedding Reception','Guest Welcome · 11:00 AM','Cana at Silang','Paglinawan Street, Pook 1<br>Silang, Cavite')}</div><section id="map" class="section journey"><h2>The Journey Continues</h2><p class="subtitle">From the Ceremony to the Celebration.</p><div class="route-art">{artwork('journey-map','Schematic pixel-art route from a church to a garden reception pavilion')}</div><div class="route-labels"><p>San Antonio de Padua Parish</p><span aria-hidden="true">→</span><p>Cana at Silang</p></div><p class="small muted">An illustrated journey, not a road map.</p><a class="btn btn-outline" data-journey-directions href="https://www.google.com/maps/dir/?api=1&amp;origin=San+Antonio+de+Padua+Parish+Pooc+Silang+Cavite&amp;destination=Cana+at+Silang+Paglinawan+Street+Pook+1+Silang+Cavite" target="_blank" rel="noopener noreferrer">Open Directions →</a></section><section id="timeline" class="section"><div class="section-heading"><h2>Game Day Timeline</h2><p class="subtitle">A little guide to the day ahead.</p></div><ol class="timeline">{timeline}</ol></section>''')

OUTFIT_ASSETS = {
    'For Women': 'guest-woman', 'For Men': 'guest-man',
    'Fathers of the Couple': 'fathers', 'Best Man': 'best-man',
    'Groomsmen & Secondary Sponsors': 'groomsmen', 'Kids — Entourage': 'kids',
    'Mothers of the Couple': 'mothers', 'Maid of Honor': 'maid-of-honor',
    'Bridesmaids & Secondary Sponsors': 'bridesmaids', 'Flower Girl': 'flower-girl',
}

men = [('Fathers of the Couple','#839aae',['Dusty Blue 3-Piece Suit','White Longsleeves','Navy Blue Neck Tie'],True,False),('Principal Sponsors','#4a4c50',['Dark Gray 2-Piece Suit','White Longsleeves','Navy Blue Neck Tie'],False,False),('Best Man','#b6b9bc',['Light Gray 3-Piece Suit','White Longsleeves','Navy Blue Neck Tie'],True,False),('Groomsmen & Secondary Sponsors','#b6b9bc',['Light Gray 2-Piece Suit','White Longsleeves','Navy Blue Neck Tie'],False,False),('Kids — Entourage','#adcadf',['Baby Blue Vest & Pants','White Longsleeves','Navy Blue Bow Tie'],True,True)]
women = [('Mothers of the Couple','#bb8994',['Dusty Rose / Dusty Pink','Mauve']),('Principal Sponsors','#e7bbc4',['Light Pink / Blush Pink']),('Maid of Honor','#7c293d',['Burgundy with a touch of Pink']),('Bridesmaids & Secondary Sponsors','#7c293d',['Burgundy']),('Flower Girl','#efc6d0',['Baby Pink'])]
def role_card(name,color,items,style='suit',vest=False,child=False):
    asset = ('female-sponsors' if style == 'dress' else 'male-sponsors') if name == 'Principal Sponsors' else OUTFIT_ASSETS[name]
    illustration = artwork('outfits/' + asset, name + ': ' + ', '.join(items), 'outfit-illustration')
    return f'<article class="outfit-card">{illustration}<h3>{escape(name)}</h3><span class="role-swatch" style="--swatch:{color}" aria-hidden="true"></span><ul>'+''.join(f'<li>{escape(x)}</li>' for x in items)+'</ul></article>'
men_cards = ''.join(role_card(n,c,i,vest=v,child=k) for n,c,i,v,k in men)
women_cards = ''.join(role_card(n,c,i,'dress') for n,c,i in women)
palette = ''.join(f'<li><span style="--swatch:{c}"></span><strong>{n}</strong><small>{c}</small></li>' for n,c in [('Charcoal Clay','#3A2B20'),('Rustic Taupe','#7E6A52'),('Warm Beige','#B89C82')])
faq_section = SPEC.split('## Frequently Asked Questions')[1].split('## Gifts')[0]
faqs = []
for question, body in re.findall(r'### (.*?)\n(.*?)(?=\n### |\Z)', faq_section, re.S):
    answer = ' '.join(line[2:].strip() for line in body.splitlines() if line.startswith('> '))
    if question == 'What should I wear?':
        answer = 'Please see our Outfit Guide for the dress code, colors, and attire inspiration. <a class="text-link" href="outfit.html#outfit">View Outfit Guide →</a>'
    else:
        answer = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', escape(answer))
    if question == 'Who can I contact on the wedding day?': answer += ' <span data-coordinator>Contact details to follow.</span>'
    faqs.append(f'<details class="faq-item"><summary>{escape(question)}</summary><p>{answer}</p></details>')

guest_content = f'''<section id="outfit" class="section"><div class="section-heading"><h2>Outfit Guide</h2><p class="subtitle">Dress for the celebration.</p></div>{tabs('outfits',[('guests','Guests'),('entourage','Wedding Entourage')])}<section id="guests" data-panel="outfits" class="tab-panel"><div class="section-heading"><p class="eyebrow">Dress Code</p><h3 class="dress-code">Semi-Formal to Smart Casual</h3></div><ul class="palette">{palette}</ul><p class="narrow">Please wear colors within or close to the tones above. Exact match is not required. We simply ask that your attire falls within these neutral earth-tone shades to create a cohesive and elegant celebration.</p><p class="narrow muted">Similar shades are welcome, including chocolate brown, espresso, mocha, mushroom taupe, camel, sand, champagne beige, and latte.</p><aside class="note avoid-note"><h3>Please Avoid</h3><p>White, Ivory, or Cream · Bright or Neon Colors · Bold Prints and Patterns</p></aside><div class="outfit-grid guest-examples">{role_card('For Women','#7E6A52',['An earth-tone midi dress','Comfortable dress shoes'],'dress')}{role_card('For Men','#B89C82',['A collared shirt and tailored trousers','Dress shoes'])}</div><p class="small muted text-center">Illustrations are a guide to color and style.</p></section><section id="entourage" data-panel="outfits" class="tab-panel">{tabs('entourage-roles',[('men','Men'),('women','Women')])}<section id="men" data-panel="entourage-roles" class="tab-panel"><h3 class="sr-only">Men’s Entourage</h3><div class="outfit-grid">{men_cards}</div><aside class="supplier"><p class="eyebrow">Recommended Suit Supplier</p><h3>Gardini Silang Branch</h3><a class="text-link" href="tel:+639099393710">0909 939 3710</a><p>Please mention that you are part of Gica &amp; Vho’s wedding when coordinating so they can refer to the appropriate attire guide.</p></aside></section><section id="women" data-panel="entourage-roles" class="tab-panel"><h3 class="sr-only">Women’s Entourage</h3><div class="outfit-grid">{women_cards}</div></section></section></section><section id="faqs" class="section"><div class="section-heading"><h2>FAQ &amp; Gifts</h2><p class="subtitle">Everything else you might want to know.</p></div><aside class="note">{pixel_icon("envelope")}<h3>A Little Note About Our Guest List</h3><p>We would truly love to celebrate with everyone, but with limited seating available, we hope you understand that we can only accommodate the guests included in each invitation.</p></aside><div class="faq-list">{''.join(faqs)}</div><section id="gifts" class="gifts">{artwork("invitation-still-life", "", "stationery-art")}<h2>Your Presence Is the Greatest Gift</h2><p>Your presence on our wedding day is already the greatest gift we could ask for. Should you wish to give something more, a monetary gift toward our next chapter together would be sincerely appreciated.</p></section></section>'''
outfit_content, faq_content = guest_content.split('<section id="faqs"', 1)
page('outfit.html', 'Outfit Guide', outfit_content.replace('<h2>Outfit Guide</h2>', '<h1>Outfit Guide</h1>'))
page('faq-gifts.html', 'FAQ & Gifts', '<section id="faqs"' + faq_content.replace('<h2>FAQ &amp; Gifts</h2>', '<h1>FAQ &amp; Gifts</h1>'))

page('gallery.html','Gallery', intro('Gallery','Before the wedding day, a little glimpse of us.') + f'''<section class="section gallery-story"><h2>Our Pre-Wedding Story</h2><section class="video-section"><h3 class="eyebrow">Save the Date Video</h3><div class="video-feature" data-video-container><p>Our save the date film is coming soon.</p><button type="button" class="btn" data-play-video disabled>Play Video</button></div></section><section class="slideshow-section"><h3>Prenup Slideshow</h3><p class="gallery-empty" data-gallery-empty>Our pre-wedding photographs will be shared here soon.</p><div class="slideshow" data-slideshow hidden><button class="slide-main" data-enlarge aria-label="Enlarge photograph"><img data-slide-image alt=""></button><div class="slide-controls"><button class="arrow" data-prev aria-label="Previous photograph">←</button><span data-photo-counter aria-live="polite"></span><button class="arrow" data-next aria-label="Next photograph">→</button></div><progress data-photo-progress aria-label="Photo progress" max="1" value="1"></progress><div class="thumbnails" data-thumbnails aria-label="Choose photograph"></div></div></section></section><section class="closing section"><h2>Memories Collected {HEART}</h2><p class="subtitle">And many more still to come.</p></section><dialog class="lightbox" data-lightbox aria-label="Enlarged photograph"><button class="lightbox-close" data-lightbox-close aria-label="Close photograph">×</button><img data-lightbox-image alt=""><div class="slide-controls"><button class="arrow" data-lightbox-prev aria-label="Previous photograph">←</button><button class="arrow" data-lightbox-next aria-label="Next photograph">→</button></div></dialog>''','<script src="js/gallery.js" defer></script>')
page('rsvp.html','RSVP', intro('RSVP','We hope you’ll be there to celebrate with us.') + '''<section class="section rsvp-gateway"><img class="stationery-art" src="assets/pixel/invitation-still-life.png" alt="" loading="lazy"><p>Kindly respond by</p><h2 class="rsvp-date">January 16, 2027</h2><p>We’ve reserved a place for you in our celebration. Please use our RSVP system below to confirm your attendance.</p><a class="btn" data-rsvp-link role="link" aria-disabled="true">Confirm Your RSVP</a><p class="small muted">You will be redirected to our RSVP system.</p><p class="small" data-rsvp-status>The RSVP link will be available soon.</p><noscript><p>Please enable JavaScript to access the RSVP link.</p></noscript></section><aside class="section note rsvp-reminder"><h2>A Little RSVP Reminder</h2><p>Each invitation has a specific number of reserved seats. As our seating arrangements are carefully planned, <strong>reserved seats are non-transferable</strong> and may not be given to another person.</p><p>If you decline the invitation, your seat may be reallocated as we finalize our guest arrangements, and <strong>we may no longer be able to accommodate changes afterward.</strong></p></aside>''')

for name, target in {'story.html':'index.html#story','map.html':'wedding.html#map','party.html':'outfit.html#entourage','gifts.html':'faq-gifts.html#gifts','thank-you.html':'rsvp.html'}.items():
    (ROOT/name).write_text(f'<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><meta http-equiv="refresh" content="0;url={target}"><title>Gica &amp; Vho</title><link rel="stylesheet" href="css/global.css"></head><body><main class="section text-center"><p>This page has moved.</p><a href="{target}">Continue to our wedding website →</a></main></body></html>',encoding='utf-8')
(ROOT/'guide.html').write_text(f'''<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Guest information · Gica &amp; Vho</title><script src="{versioned('js/redirect-guide.js')}" defer></script><link rel="stylesheet" href="{versioned('css/global.css')}"></head><body><main class="section text-center"><h1>Guest information</h1><p><a href="outfit.html">Outfit Guide</a></p><p><a href="faq-gifts.html">FAQ &amp; Gifts</a></p></main></body></html>''', encoding='utf-8')
print('Built 6 pages and 6 legacy redirects/compatibility pages.')
